---
# Source: gha-runner-scale-set-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-scaleset-controller-gha-rs-controller
  namespace: gh-scaleset-controller
  labels:
    helm.sh/chart: gha-rs-controller-0.11.0
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: gh-scaleset-controller
    app.kubernetes.io/instance: gh-scaleset-controller
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/managed-by: Helm
---
# Source: gha-runner-scale-set-controller/templates/manager_cluster_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gh-scaleset-controller-gha-rs-controller
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - list
  - watch
  - patch
---
# Source: gha-runner-scale-set-controller/templates/manager_cluster_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gh-scaleset-controller-gha-rs-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gh-scaleset-controller-gha-rs-controller
subjects:
- kind: ServiceAccount
  name: gh-scaleset-controller-gha-rs-controller
  namespace: gh-scaleset-controller
---
# Source: gha-runner-scale-set-controller/templates/manager_listener_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-scaleset-controller-gha-rs-controller-listener
  namespace: gh-scaleset-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set-controller/templates/manager_listener_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-scaleset-controller-gha-rs-controller-listener
  namespace: gh-scaleset-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gh-scaleset-controller-gha-rs-controller-listener
subjects:
- kind: ServiceAccount
  name: gh-scaleset-controller-gha-rs-controller
  namespace: gh-scaleset-controller
---
# Source: gha-runner-scale-set-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-scaleset-controller-gha-rs-controller
  namespace: gh-scaleset-controller
  labels:
    helm.sh/chart: gha-rs-controller-0.11.0
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: gh-scaleset-controller
    app.kubernetes.io/instance: gh-scaleset-controller
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/managed-by: Helm
    actions.github.com/controller-service-account-namespace: gh-scaleset-controller
    actions.github.com/controller-service-account-name: gh-scaleset-controller-gha-rs-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/namespace: gh-scaleset-controller
      app.kubernetes.io/instance: gh-scaleset-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: "manager"
      labels:
        app.kubernetes.io/part-of: gha-rs-controller
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/version: 0.11.0
        app.kubernetes.io/name: gha-rs-controller
        app.kubernetes.io/namespace: gh-scaleset-controller
        app.kubernetes.io/instance: gh-scaleset-controller
    spec:
      serviceAccountName: gh-scaleset-controller-gha-rs-controller
      containers:
      - name: manager
        image: "ghcr.io/actions/gha-runner-scale-set-controller:0.11.0"
        imagePullPolicy: IfNotPresent
        args:
        - "--auto-scaling-runner-set-only"
        - "--log-level=debug"
        - "--log-format=text"
        - "--runner-max-concurrent-reconciles=2"
        - "--update-strategy=immediate"
        - "--listener-metrics-addr=0"
        - "--listener-metrics-endpoint="
        - "--metrics-addr=0"
        command:
        - "/manager"
        env:
        - name: CONTROLLER_MANAGER_CONTAINER_IMAGE
          value: "ghcr.io/actions/gha-runner-scale-set-controller:0.11.0"
        - name: CONTROLLER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tmp
        emptyDir: {}
