kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.trial.studio
      tls:
        - secretName: grafana-cm-tls
          hosts:
            grafana.trial.studio