{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-scale-set-primary-vault-secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gh-scale-set-primary-vault-secret
spec:
  provider:
    vault:
      server: "http://vault-active.vault:8200"
      path: system/gh-scale-set-primary
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: gh-scale-set-primary
          serviceAccountRef:
            name: gh-scale-set-primary-vault-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-scale-set-primary-vault-secret
spec:
  secretStoreRef:
    name: gh-scale-set-primary-vault-secret
    kind: SecretStore
  target:
    name: gh-scale-set-primary-vault-secret
  data:
    - remoteRef:
        key: application
        property:  github_app_id
      secretKey:  github_app_id
    - remoteRef:
        key: application
        property:  github_app_installation_id
      secretKey:  github_app_installation_id
    - remoteRef:
        key: application
        property:  github_app_private_key
      secretKey:  github_app_private_key
{{ end }}
