{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: i.bacangan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - selector:
          dnsZones:
            - "trial.studio"
        dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z06285332QCWSWF1RDQBK
            accessKeyIDSecretRef:
              name: cert-manager-vault-secret
              key: access-key
            secretAccessKeySecretRef:
              name: cert-manager-vault-secret
              key: secret-key
{{ end }}