{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: cert-manager-vault-secret
spec:
  path: /aws-daily/creds/cert-manager
  method: GET
  provider:
    server: "http://vault-active.vault:8200"
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cert-manager-vault-secret
        serviceAccountRef:
          name: cert-manager-vault-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-vault-secret
spec:
  refreshInterval: 16h
  target:
    name: cert-manager-vault-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: cert-manager-vault-secret
{{ end }}