apiVersion: v2
name: alloy
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: alloy
    version: 0.12.5
    repository: https://grafana.github.io/helm-charts
    alias: daemonset
#  - name: alloy
#    version: 0.9.1
#    repository: https://grafana.github.io/helm-charts
#    alias: apps